journey: main.c Flight.c Train.c Bus.c Reservation.c bus.h flight.h reservation.h Train.h 
	@gcc main.c Flight.c Train.c Bus.c Reservation.c bus.h flight.h reservation.h Train.h -o journey

clean:
	$ rm -rf journey



